name: bkclient_flutter
description: Flutter bkclient.
version: 0.0.1
author:
homepage: https://github.com/bunker89/BKClient-flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.keyanist.bkclient.bkclient_flutter
        pluginClass: BkclientFlutterPlugin
      ios:
        pluginClass: BkclientFlutterPlugin
