name: bkclient_flutter
description: Flutter bkclient.
version: 0.0.8
homepage: https://github.com/bunker89/bkclient_flutter

environment:
  sdk: '>=2.12.0 <=3.6.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.keyanist.bkclient.bkclient_flutter
        pluginClass: BkclientFlutterPlugin
      ios:
        pluginClass: BkclientFlutterPlugin
